baseURL: https://heal.lgbt/
title: Queer Healing Resources
publishDir: docs/
googleAnalytics: UA-125560-7
languageCode: en-us
enableEmoji: true
enableGitInfo: true
disableKinds: ['taxonomy']
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
